README.md, src/cli.js
=> Fix issue 1

package.json
Reverts tsuyoshiwada/storybook-chrome-screenshot#12
=> Revert "Feature: Module"

CHANGELOG.md, package.json, src/internal/server.js, yarn.lock
Fixed processing to judge whether storybook server started.
It corresponds to the output of URL changed from `stdout` to `stderr`.
=>  Fix crash bug with storybook v3.3.x

src/cli.js
Fix #22 .
I've published this change to my NPM scope and use it from CircleCI job, it work perfectly 😄 
See https://circleci.com/gh/Quramy/angular-sss-demo/4 .
=> fix puppeteer launch on Linux based CI

.circleci/config.yml, README.md, examples/angular-cli/package.json, package.json, scripts/e2e.sh
What I did:
- Create e2e testing script
- Create Circle CI conf
To run the above on CI, please turn on Circle CI build(go to https://circleci.com/add-projects/gh/tsuyoshiwada ) 😄 
The following log was captured at my forked repo:
https://circleci.com/gh/Quramy/storybook-chrome-screenshot/6
=> add e2e script

README.md
Add missing brackets in example.
=> Add missing brackets in example

README.md
Add link to a tutorial repository for setting up visual regression testing with VisWiz.io.
=> Add tutorial repository example

src/cli.ts, src/core/app/App.ts
I think it would be nice to log error when some unexpected occurred 🙏
=> Log when something is wrong

src/core/app/App.ts, src/core/app/Page.ts
This PR just provide a proper async flow for parallel rendering (#39) , and meanwhile fixing a strange console-related issue.
=> Fix parallel rendering

src/cli.ts, src/core/app/App.ts, src/core/app/Browser.ts, src/core/app/Page.ts, src/core/client/AppAdapter.ts, src/core/client/Client.ts, src/core/client/Gateway.ts
Hi, this PR makes the PREPARE phase parallelize with the `--parallel` option, which is going on my task left from #50 :)
=> Perf tune on prepare phase

README.md, src/core/__tests__/utils.test.ts, src/core/app/App.ts, src/core/app/StoryStore.ts, src/core/constants.ts, src/core/utils.ts, src/models/options.ts, src/models/story.ts
Related to #42 
Adding ability to customize saving file pattern, but it is not "feature complete" as long fileName is not passed here.
Could you help me to make this real?
=> Add file saving pattern

packages/storycap/package.json, packages/storycap/src/node/file.ts, yarn.lock
=> fix: sanitize unsafe filename chars

packages/storycrawler/package.json
Hey reg-viz! We've created a catalog of Storybook addons like yours: https://storybook.js.org/addons
To make your addon more discoverable in the catalog, we've curated some of its metadata, and I've included those edits in this PR.
To learn more about the catalog metadata, check out our documentation: https://storybook.js.org/docs/react/addons/addon-catalog
=> Update Storybook addon metadata

README.md
=> Fix vue kitchen sink's url

examples/v4-managed-react/package.json, examples/v4-simple/package.json, examples/v5-managed-react-legacy-decorator/package.json, examples/v5-managed-vue/package.json, examples/v5-simple/package.json, examples/v6-managed-react/package.json, examples/v6-simple/package.json, packages/storycap/src/node/main.ts
Sometimes Storycap process hangs up during execution. 
Example: https://app.circleci.com/pipelines/github/reg-viz/storycap/1179/workflows/f2711045-a5bf-4847-89d1-920d05bb9af3/jobs/1888
We should investigate which promise is pending.
=> chore: Add debug logs to inspect pending promise

packages/storycap/src/node/capturing-browser.ts
=> fix: Force reload if isMobile prop changes

packages/storycrawler/src/browser/resource-watcher.ts
=> fix: Skip to watch non HTTP request

packages/storycap/src/node/capturing-browser.ts
=> fix focus, hover and click bug resolve #580

packages/storycap/src/node/capturing-browser.ts
=> fix mouse position leaking to other screenshots 

packages/storycap/package.json, packages/storycap/src/node/cli.ts, yarn.lock
=> chore: Upgrade yargs
