src/cli.ts, src/core/app/App.ts, src/core/app/Browser.ts, src/core/utils.ts
I've created this for #7 :)
This PR makes parallelization in the `CAPTURE` phase more efficient. It because that considering TCP connection restrictions of Chromium, parallelization of browser processes can use CPU more efficiently than parallelization of pages in one browser process.
=> Parallelize browser processes rather than pages

src/core/app/Page.ts, src/core/constants.ts
Hello,
I'm running across an issue where the current default behavior of taking a screenshot at the same height of the page is causing the image of a modal to be truncated. This seems to be because `documentElement.scrollHeight` (used [here](https://github.com/tsuyoshiwada/storybook-chrome-screenshot/blob/master/src/core/client/Client.ts#L60)) does not return consistent results across browsers.
This PR proposes a change where it uses the height that has been set in the viewport config for the screenshot and only defaults to using the height of the page if nothing has been set.
Thank you for taking the time to look at this.
=> Fix: Use the height that has been set in the viewport config for the screenshot

README.md, examples/v5-managed-react/.storybook/config.js, examples/v5-managed-react/src/stories/index.js, examples/v5-simple/package.json, src/client/capture.ts, src/client/default-screenshot-options.ts, src/client/types.ts, src/node/capturing-browser.ts, src/node/cli.ts, src/node/screenshot-service.ts, src/node/story-crawler/browser/story-preview-browser.ts, src/node/types.ts, src/util/screenshot-options-helper.test.ts, src/util/screenshot-options-helper.ts
This PR allows to configure multiple viewports.
- CLI accepts `-V` as an array
- ScreenshotOptions accepts `viewports` section
Multiple viewports should be expanded as one default viewport and viewport variants that represent the rest of them.
See also #95
=> V2 multiple viewports

examples/v5-managed-react/src/stories/index.js, src/client/types.ts, src/node/capturing-browser.ts, src/util/screenshot-options-helper.test.ts, src/util/screenshot-options-helper.ts
Introduce `extends` keyword into variants definition.
```js
screenshot: {
variants: {
iPad: { viewport: 'iPad' },
hover: {
hover: 'button',
extends: 'iPad',
},
}
```
For example, the above options generates:
- `some_kind/some_story.png` (default variant
- `some_kind/some_story_iPad.png`
- `some_kind/some_story_iPad_hover.png`
See also #95  (originally it was named as `followWith` )
=> feat: allow to extend other variables

MIGRATION.md, README.md, examples/v5-managed-react/src/stories/index.js, packages/storycap/package.json, packages/storycap/src/client/is-screenshot.ts, packages/storycap/src/index.ts, packages/storycap/tsconfig.client.json
- Add `isScreenshot` function ( closes #105 )
- Downpile client's sources with `--target es5` ( closes #131 )
=> Add function to get whether is in storycap

packages/storycap/src/client/trigger-screenshot.ts, packages/storycap/src/client/with-screenshot.ts
At the moment there is an issue with storyshots. I get the following exception (line numbers can differ because it was from my local version with some extra log messages):
|         return kind + "/" + story;
76 |     }
> 77 |     throw new Error();
|           ^
78 | }
79 | function waitForDelayTime(time) {
80 |     if (time === void 0) { time = 0; }
at url2StoryKey (../../itcb/storycap/packages/storycap/lib/client/trigger-screenshot.js:77:11)
at url2StoryKey (../../itcb/storycap/packages/storycap/lib/client/trigger-screenshot.js:126:16)
at Object.stock [as triggerScreenshot] (../../itcb/storycap/packages/storycap/lib/client/trigger-screenshot.js:200:5)
at triggerScreenshot (../../itcb/storycap/packages/storycap/lib/client/with-screenshot.js:16:34)
at …
=> Correct behavior with storyshots

examples/v5-managed-react/src/stories/index.js, packages/storycap/src/node/capturing-browser.ts
- Set hover & focus variants in the story ([source](#)).
- Run `$ ./e2e.sh examples/v5-managed-react`.
- By trying several times, We can look hover state in the focused screenshot image.
I'm guessing that it bugs related to virtual DOM behavior :bulb:
Storybook is a single page application. So, there is a possibility that the same DOM is used in the surrounding stories.
In the case of a Story with hover and focus states, I think that the next state of the screenshot would retain the previous state. So, there will be cases where the Hover state will remain in the screenshot you tried to take in the Focus state.
I added emulate the logic of browser behavior to `CapturingBrowser#resetIfTouched` method (reset states process).
```typescript
// Clear the browser state.
await …
```
=> Fix a screenshot bug when using hover & focus state at the same story

packages/storycrawler/src/browser/stories-browser.ts
Suppress warning message about Puppeteer deprecated `waitFor` function
=> fix: don't use waitFor function

README.md, packages/storycap/src/node/capturing-browser.ts, packages/storycap/src/shared/screenshot-options-helper.ts, packages/storycap/src/shared/types.ts
This closes #287.
This PR adds an `omitBackground` option that gets passed through to the browser that can be used to take screenshots with a transparent background.
=> feat: added omitBackground option

packages/storycap/src/node/errors.ts
I think it has typo.
`triggerd` -> `triggered`
=> fix typo: triggerd -> triggered

README.md, packages/storycap/src/node/capturing-browser.ts, packages/storycap/src/shared/screenshot-options-helper.ts, packages/storycap/src/shared/types.ts
As of puppeteer-core v7.0.0, if the content exceeds the viewport, everything will be captured.
https://github.com/puppeteer/puppeteer/tree/v7.0.0
> ⚠ BREAKING CHANGES
> page.screenshot makes a screenshot with the clip dimensions, not cutting it by the ViewPort size.
> chromium: - page.screenshot cuts screenshot content by the ViewPort size, not ViewPort position.
This change caused screenshots to be taken in a different condition than expected.
In puppeteer-core v9.0.0, the captureBeyondViewport option has been introduced, allowing you to clip at the viewport as in the old behavior.
https://github.com/puppeteer/puppeteer/pull/7063
https://github.com/puppeteer/puppeteer/blob/v13.1.3/docs/api.md#pagescreenshotoptions
> captureBeyondViewport <boolean>
> When true, captures screenshot beyond …
=> feat: add captureBeyondViewport option to SnapshotOptions

package.json, packages/storycap/src/node/capturing-browser.ts
The bug occurs when using a viewport with `hasTouch` or `isMobile`, or when a page reload is performed using the `reloadAfterChangeViewport` flag. The `disableCssAnimation` is not enabled for shots taken after a page reload.
I've modified the logic to add an element to disable CSS Animation again on page reload.
See [wadackel/storycap-reproduce-viewport-bug](https://github.com/wadackel/storycap-reproduce-viewport-bug).
| `Default_iPad`                      | `Default_iPhone11`                      |
| ----------------------------------- | --------------------------------------- |
| ![](https://raw.githubusercontent.com/wadackel/storycap-reproduce-viewport-bug/main/actual/Test/Default_iPad.png) | ![](https://raw.githubusercontent.com/wadackel/storycap-reproduce-viewport-bug/main/actual/Test …
=> Fix disableCssAnimation bug when using multiple viewports

packages/storycap/decl/storybook.d.ts, packages/storycap/src/client/register.ts
Hi,
In storybook v7, default export of `@storybook/addons` will be removed.
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-default-export-from-storybookaddons
When I run storycap in 7.0.0-alpha.26, I got this error. This PR would fix it.
```
register.js:8 Uncaught TypeError: addons_1.default.register is not a function
at node_modules/storycap/lib/client/register.js (register.js:8:18)
at __require (register.mjs:9:50)
at node_modules/storycap/register.js (register.js:1:18)
at __require (register.mjs:9:50)
at register.js:1:18
node_modules/storycap/lib/client/register.js @ register.js:8
__require @ register.mjs:9
node_modules/storycap/register.js @ register.js:1
__require @ register.mjs:9
（匿名） @ register.js:1
```
=> Use named export of @storybook/addons

packages/storycap/src/node/capturing-browser.ts
`exposeFunction` should be awaited as per [the docs](https://pptr.dev/api/puppeteer.page.exposefunction/)
Closes https://github.com/reg-viz/storycap/issues/631
=> bug: Fixed exposeFunction not being awaited

renovate.json
I'd recommend having non-breaking minor updates automatically added to the main branch. That lessens maintenance work on all those frequent PRs!
You'd only be having a PR for major releases or releases that break the build pipeline.
=> ci(renovate): automerge non-breaking minor updates, update lockfile

packages/storycap/package.json, packages/storycrawler/package.json
When I ran the test, there were several warnings, so I changed the settings for each of them.
Please see the commit message for details.
- fix(test): replace testURL options to testEnvironmentOptions.url
- fix(jest): replace ts-jest config to transform
- fix(jest): added files with .tsx extension to the transform target
=> fix: solve a problem with warnings during test execution

README.md, packages/storycap/src/node/capturing-browser.ts, packages/storycap/src/shared/screenshot-options-helper.ts, packages/storycap/src/shared/types.ts
Sometimes, especially in situations with `play` functions, we may need to adjust some of the UI but only be interested in taking a screenshot of a portion of the UI. This allows us to specify what portion of the screen we want the screenshot taken.
To some extent resolves #506 (this does not allow passing a selector string, but it is easy to convert a selector string to a bounding box, and using a bounding box provides us more flexibility).
=> Add the ability to screenshot a part of the screen

README.md, packages/storycap/src/node/cli.ts
I think it is a typo.
`shot` → `host`
=> fix typo: localshot -> localhost

packages/storycap/src/node/file.ts
This PR refactors the FileSystem class to use `fs/promises` (available since Node 10) for all filesystem operations, instead of synchronously building folders with mkdirp, and re-building a promise to write the file.
=> chore: Use fs promises for filesystem APIs

README.md, packages/storycap/src/node/capturing-browser.ts, packages/storycap/src/node/cli.ts, packages/storycap/src/node/main.ts, packages/storycap/src/node/screenshot-service.ts, packages/storycap/src/node/types.ts, packages/storycap/src/shared/screenshot-options-helper.ts
This builds on https://github.com/reg-viz/storycap/pull/789, happy to rebase as needed.
Currently the screenshot utility swallows all console logs and errors from the 'story' context. This makes debugging screenshots extremely difficult. (It's also quite difficult to mount a debugger to the internal story isolate.)
This PR forwards console messages by default into the `debug` Logger channel, and optionally allows for a `--forwardConsoleLogs` option to surface them to the user's CLI with matched `error`, `warn` or `info` log levels.
Messages currently look like:
`error From examples-thrusttestbench--screenshot-light (error): THREE.WebGLRenderer: Error creating WebGL context.`
Happy to bikeshed the cli option name, format of the logs, etc.
=> Forward console logs from the story context to the user's CLI

README.md, packages/storycap/src/node/capturing-browser.ts, packages/storycap/src/node/cli.ts, packages/storycap/src/node/file.ts, packages/storycap/src/node/main.ts, packages/storycap/src/node/screenshot-service.ts, packages/storycap/src/node/types.ts, packages/storycap/src/shared/screenshot-options-helper.ts
This builds on https://github.com/reg-viz/storycap/pull/790 and https://github.com/reg-viz/storycap/pull/789, happy to rebase as needed.
When debugging performance problems with screenshots, it's helpful to have a flamegraph of what's taking time.
It's difficult to mount a debugger into the internal story isolate. This PR enables a `--trace` cli option that records a Chromium CPU trace of the screenshot and saves it alongside the screenshot `filename.png` as `filename_trace.json`.
This trace can be imported into Chrome's Performance Flamegraph or https://ui.perfetto.dev/ for viewing.
This is especially helpful for situations like:
Despite the screenshot not succeeding, the trace of the last attempt will still be written, and we can plainly see that this particular screenshot continues …
=> Record CPU traces from screenshot runs

packages/storycap/src/node/capturing-browser.ts
- Rerender story **after** the cleanup events have been fired
- Remove workaround from #712
=> #806 Fix "failed to find element"

README.md, packages/storycap/src/node/capturing-browser.ts
Some links in the README and comment to the puppeteer repository were broken, so I have updated them.
None
None
Not Bug
=> chore: fix external link in the README

lerna.json, packages/storycap/package.json, packages/storycrawler/package.json, packages/storycrawler/src/browser/stories-browser.ts, yarn.lock
It may fix #896.
After Chromium 128 (linux),  timeout error occurs during `StoriesBrowser#getStories()` method.
We do not know why Chromium is timing out. However, since this method involves waiting for the Preview API function to be exposed, I see no need to wait for this goto method to complete.
=> fix: Stop wait to navigate preview html
